Repository mozilla/fxa-oauth-server, pull requests merged in 2018-10, with the labels that each got.

#607 feat(openid): add `fxa-profileChangedAt` to /verify
  lib/browserid.js
  lib/db/memory.js
  lib/db/mysql/index.js
  lib/db/mysql/patch.js
  lib/db/mysql/patches/patch-021-022.sql
  lib/db/mysql/patches/patch-022-021.sql
  lib/db/mysql/schema.sql
  lib/routes/authorization.js
  lib/routes/token.js
  lib/routes/verify.js
  lib/token.js
  test/api.js
  test/browserid.js
Labels: waffle:review

#610 Release v1.122.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#612 fix(db): Drop foreign key constraints.
  lib/db/mysql/index.js
  lib/db/mysql/patch.js
  lib/db/mysql/patches/patch-022-023.sql
  lib/db/mysql/patches/patch-023-022.sql
  lib/db/mysql/schema.sql
Labels: waffle:review

#613 fix(db): Fix case-consistency of SQL query from #612
  lib/db/mysql/index.js
Labels: waffle:review

#614 Release v1.123.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#615 feat(deps): update to bluebird 3
  lib/db/mysql/index.js
  npm-shrinkwrap.json
  package.json
Labels: auto-merge, waffle:active

#616 fix(deps): update mocha and other dev deps
  coverage/blanket.js
  npm-shrinkwrap.json
  package.json
  scripts/test-local.sh
  test/auth_bearer.js
  test/db/mysql.js
Labels: auto-merge, waffle:review

#617 feat(server): update to Hapi 17
  .eslintrc
  bin/internal.js
  bin/server.js
  lib/auth.js
  lib/auth_bearer.js
  lib/db/memory.js
  lib/db/mysql/index.js
  lib/routes/authorization.js
  lib/routes/client-tokens/delete.js
  lib/routes/client-tokens/list.js
  lib/routes/client/delete.js
  lib/routes/client/get.js
  lib/routes/client/list.js
  lib/routes/client/register.js
  lib/routes/client/update.js
  lib/routes/config.js
  lib/routes/destroy.js
  lib/routes/developer/activate.js
  lib/routes/heartbeat.js
  lib/routes/jwks.js
  lib/routes/key_data.js
  lib/routes/redirect.js
  lib/routes/root.js
  lib/routes/token.js
  lib/routes/verify.js
  lib/server/config.js
  lib/server/index.js
  lib/server/internal.js
  npm-shrinkwrap.json
  package.json
  test/auth_bearer.js
  test/db/mysql.js
  test/hpkp.js
  test/lib/server.js
Labels: waffle:review

#618 fix(2fa): Allow an explicit `null` value for `acr_values` param.
  lib/routes/authorization.js
Labels: blocker, waffle:review

#621 fix(profile): remove the `profileChangedAt` colum on tokens table
  lib/db/memory.js
  lib/db/mysql/index.js
  lib/db/mysql/patch.js
  lib/db/mysql/patches/patch-023-024.sql
  lib/db/mysql/patches/patch-024-023.sql
  lib/db/mysql/schema.sql
  test/api.js
Labels: waffle:active

#623 fix(db): Restore foreign key constraints on core tables.
  lib/db/mysql/patch.js
  lib/db/mysql/patches/patch-024-025.sql
  lib/db/mysql/patches/patch-025-024.sql
Labels: shipit, train-123, waffle:active
