Repository mozilla/fxa-oauth-server, pull requests merged in 2018-04, with the labels that each got.

#534 feat(oauth): make server compatible with AppAuth
  lib/routes/token.js
  lib/validators.js
  test/api.js
Labels: shipit, train-109, waffle:active

#540 feat(email-first): Add support for the email-first flow.
  docs/api.md
  lib/routes/redirect.js
  test/api.js
Labels: waffle:review

#541 feat(authorization): Directly return `code` in authorization response.
  lib/routes/authorization.js
  test/api.js
Labels: waffle:review

#546 fix(oauth): another notes dev client
  config/dev.json
Labels: waffle:active

#544 feat(node): update to node 8
  .travis.yml
  Dockerfile-build
  package.json
Labels: waffle:active

#548 fix(validation): Allow redirect uris with existing query params.
  lib/validators.js
  test/api.js
Labels: waffle:active
