Repository mozilla/fxa-oauth-server, pull requests merged in 2018-08, with the labels that each got.

#586 fix(ci): Run MySQL tests in Circle
  .circleci/config.yml
Labels: waffle:review

#551 fix(scopes): Formalize and document scope-handling rules.
  docs/scopes.md
  lib/auth.js
  lib/auth_bearer.js
  lib/db/helpers.js
  lib/db/memory.js
  lib/db/mysql/index.js
  lib/routes/authorization.js
  lib/routes/client-tokens/delete.js
  lib/routes/client-tokens/list.js
  lib/routes/client/delete.js
  lib/routes/client/list.js
  lib/routes/client/register.js
  lib/routes/client/update.js
  lib/routes/developer/activate.js
  lib/routes/key_data.js
  lib/routes/token.js
  lib/routes/verify.js
  lib/scope.js
  lib/token.js
  npm-shrinkwrap.json
  package.json
  test/api.js
  test/auth_bearer.js
  test/db/helpers.js
  test/db/index.js
  test/scope.js
Labels: shipit, train-117, waffle:active

#594 fix(authorization): Correctly handle non-existing URL scopes during authorization
  lib/routes/authorization.js
  test/api.js
Labels: waffle:active

#595 Release v1.119.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#598 feat(openid): add the openid connect `at_hash` value
  lib/routes/token.js
  lib/util.js
  test/api.js
Labels: waffle:review
