Repository mozilla/fxa-oauth-server, pull requests merged in 2018-03, with the labels that each got.

#522 chore(npm): update to npm5
  npm-shrinkwrap.json
Labels: waffle:review

#526 chore(deps): Update hapi to v16.6.3
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#530 feat(amr): Report `amr` and `acr` claims in the id_token.
  lib/browserid.js
  lib/db/memory.js
  lib/db/mysql/index.js
  lib/db/mysql/patch.js
  lib/db/mysql/patches/patch-020-021.sql
  lib/db/mysql/patches/patch-021-020.sql
  lib/routes/authorization.js
  lib/routes/token.js
  package.json
  scripts/test-local.sh
  test/api.js
  test/browserid.js
Labels: waffle:active

#533 fix(route): make email false by default
  lib/routes/verify.js
  test/api.js
Labels: train-109, waffle:review

#535 fix(scripts): Fix varname typo in test runner script.
  scripts/test-local.sh
Labels: waffle:review

#536 chore(config): add Notes trailing slash to redirect in dev.json
  config/dev.json
Labels: waffle:active

#537 fix(node): Use Node.js v6.14.0
  Dockerfile-build
Labels: waffle:active
